/**
 * The products these docs cover — one entry each, in nav order.
 *
 * Before this file existed, "which product is this page?" was written out five
 * times: Head.astro (search filter), Sidebar.astro (nav tree), Footer.astro
 * (llms.txt subset), Banner.astro (status notice) and again as browser code in
 * Search.astro. Each was the same two-branch prefix test, and adding a third
 * product meant editing all five and hoping none drifted.
 *
 * Everything product-shaped now hangs off this list: the emoji that tags sidebar
 * groups and search badges, the llms.txt subset link, the status banner. Adding a
 * product is one entry here plus its content directory.
 *
 * The `id` doubles as the content-directory name and the URL prefix, so
 * `trados` ⇒ `trados/*.md` ⇒ `/trados/…`. That is what makes detection a prefix
 * test rather than a lookup table.
 *
 * `label` must match the product name used in the sidebar group labels generated
 * from SUMMARY.md, because Sidebar.astro filters top-level groups by
 * `label.includes(product.label)`.
 */

export type ProductId = 'trados' | 'memoq' | 'workbench';

export interface Product {
  id: ProductId;
  /** Short name, and the string sidebar group labels are matched against. */
  label: string;
  /** Full product name, for places with room to spell it out (the search scope pill). */
  fullName: string;
  /**
   * Shown before the label. Always used in the sidebar, where Starlight renders
   * group labels as plain text and an image is not an option; used elsewhere
   * only when `icon` is absent.
   */
  emoji: string;
  /**
   * Optional path to the product's own mark, served from public/. Preferred over
   * the emoji anywhere we render our own HTML — search badges, the scope pill,
   * the landing cards.
   */
  icon?: string;
  /** Path of the per-product llms.txt subset generated by starlight-llms-txt. */
  llmsSubset: string;
  /** Optional status notice shown across the whole product tree, as raw HTML. */
  banner?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: 'trados',
    label: 'Trados',
    fullName: 'Supervertaler for Trados',
    emoji: '🧩',
    llmsSubset: '/_llms-txt/supervertaler-for-trados.txt',
  },
  {
    id: 'memoq',
    label: 'memoQ',
    fullName: 'Supervertaler for memoQ',
    emoji: '🟠',
    icon: '/product-icons/memoq.png',
    llmsSubset: '/_llms-txt/supervertaler-for-memoq.txt',
    banner:
      '<strong>Supervertaler for memoQ is in early development.</strong> ' +
      'These pages describe what works today and will change as it does. ' +
      'The stable product is <a href="/trados/">Supervertaler for Trados</a>.',
  },
  {
    id: 'workbench',
    label: 'Workbench',
    fullName: 'Supervertaler Workbench',
    emoji: '🖥️',
    llmsSubset: '/_llms-txt/supervertaler-workbench.txt',
    banner:
      '<strong>Supervertaler Workbench is no longer actively developed.</strong> ' +
      'These pages stay online and still describe the last release. ' +
      'Active development is on <a href="/trados/">Supervertaler for Trados</a>.',
  },
];

/**
 * The product a page belongs to, from its Starlight entry id (`trados/foo`) or
 * a URL path (`/trados/foo/`). Returns null for the landing page and anything
 * else outside a product tree — those pages stay visible to every scope.
 */
export function productFor(idOrPath: string | undefined | null): Product | null {
  if (!idOrPath) return null;

  const id = idOrPath.replace(/^\/+/, '').replace(/\/+$/, '');
  return (
    PRODUCTS.find((p) => id === p.id || id.startsWith(`${p.id}/`)) ?? null
  );
}

/** Product whose `label` matches, for code that only has the display name. */
export function productByLabel(label: string | null): Product | null {
  if (!label) return null;
  return PRODUCTS.find((p) => p.label === label) ?? null;
}
